### ISSUE TITLE
Add a "skip dev dependencies" flag

### ISSUE THREAD

**Issue by omeraha** [IBM/audit-ci#133]
Add a "skip dev dependencies" flag that allows the user to skip auditing of dev dependencies.

**Comment by quinnturner** [comment]
Hi @omeraha,

Thanks for checking out the project! There has been a discussion on this topic on the pinned post: #91.

I still believe the discussion on that issue is relevant and that a skip all devDependencies is not as appropriate as manually whitelisting known and ignored vulnerabilities. Feel free to add to the discussion on that issue. I am closing this issue for now.
