### ISSUE TITLE
Support `--json` mode

### ISSUE THREAD

**Issue by G-Rath** [IBM/audit-ci#147]
I've just stumbled upon this package and have to say: it seems super cool!

My company has an internal auditor that runs the appropriate auditors against our repos, and this looks like it could be a complete drop-in that would gain us some very useful features (whitelisting in particular).

However currently `audit-ci` outputs a few lines of text before & after the JSON audit results - it would be useful if there was a `--json` flag that would have only the audit results JSON be outputted.

An extension on this could be to then add a `auditCi` property that contained information from `audit-ci`, such as what was whitelisted.

I'm happy to work on a PR for this, and have a few ideas on how to go about it - my initial attempt will likely be to just replace all log calls with a logger function call that is a noop if the flag is present.

**Comment by quinnturner** [comment]
I was wondering if someone was going to request "JSON-only" mode! Would this JSON-only mode be your desired behaviour or would the returning of the "report" object be more useful? If in JSON-only mode, you could pipe the result to a consumer and that may be sufficient.

To add a datapoint to the discussion, https://github.com/npm/npm-audit-report is an interesting project specifically for `npm`. I haven't reviewed much of it yet, but there may be lessons to be learned from that project.

Another thing to consider is that Yarn's audit isn't a single JSON object while NPM's audit is a single JSON object. It doesn't support whitelisting, but does manage the audit result in a single object that can be consumed. We use the JSON-stream dependency to manage consuming the JSON from the audits since we have had CIs fail due to too many security advisories.

Currently, the information regarding the information from the audit and whitelisting is contained within `Model.js`. I don't mind if that's refactored or if it's exported to be consumed.

**Comment by quinnturner** [comment]
For further flexibility, I would consider revising the flag from `--json` to something like `--output {none/full/json} (default full)`. This is slightly different than the `--report-type` since report-type refers to the output within either a `full` or `json`.

I am unsure if this would be a confusing semantic for adopters. Also, since Yarn uses JSON-lines format rather than JSON, that might result in a "gotcha", but this behaviour can be documented.

**Comment by G-Rath** [comment]
Those are some good questions & considerations.

Currently our auditor shells out to npm & yarn for auditing, so it handles both the json structures; the primary win here is supporting a whitelist.

However overall in theory npm 7 will make this less of a problem since it supports both package-lock.json & yarn.lock, so it should be able to audit both, giving the same output. (but that would just save you from having to implement whitelisting in yarn).

I think `--output` is a good idea, and I could see use for the `none` value. The name might need some regigging, but the outputted JSON is pretty big, and always outputted so that value could be used to shut `audit-ci` up: "only tell me what failed if things fail".

I'll have a think over this as I play with `audit-ci` during the course of the week :)

I might have a crack at implementing the whitelisting into yarn first, as we use Ruby/Rails a lot which picked yarn as their default package manager.

**Comment by quinnturner** [comment]
Also note this request has significant overlap with this feature request: https://github.com/IBM/audit-ci/issues/118

Would be nice for a solution to address both issues, but not a requirement 🙂

**Comment by LohitakshTrehan** [comment]
Hi, any update on the above feature request?

I think providing a way to output the report as a pure JSON object would be helpful in parsing the data. Checked [retireJS](https://www.npmjs.com/package/retire). It also supports flags like --outputFormat and --outputPath(to directly redirect output to a file, we can skip this if not desired). Maybe we can introduce something like this.

Regards
Lohitaksh

**Comment by quinnturner** [comment]
I have not performed any work on this feature at this time. However, I do think it is a valuable addition. I don't have immediate plans to write this feature myself (may in the future), but I would certainly review PR requests.

**Comment by keshavkaul** [comment]
Hi, what are your thoughts on SARIF output format?

**Comment by quinnturner** [comment]
@keshavkaul the more the merrier! I think having an `--outputFormat`|`--output-format` flag is very useful and SARIF is a great standard. I have no immediate plans to write that functionality at this time (JSON is an easier place to start anyways).
