### ISSUE TITLE
Not all of the output is captured causing JSON parse errors

### ISSUE THREAD

**Issue by callum-p** [IBM/audit-ci#57]
I always get this error when running against a few of my projects with similar dependencies. It seems to be caused by buffers not being flushed so not all the output is captured, or buffer size not big enough, or something like that.

Had some trouble attaching files. Logs at https://gist.github.com/callum-p/5efc1226f35ff6dacba53d950ca21f43

```
user@l0calhost:~/repos/xx/xx-xx-xx-xx(develop)$ docker run --rm -v $PWD:/analyse node:10.8.0-alpine /bin/sh -c "npm install -g audit-ci && cd /analyse && audit-ci"
/usr/local/bin/audit-ci -> /usr/local/lib/node_modules/audit-ci/bin/audit-ci
+ audit-ci@1.3.1
added 56 packages from 12 contributors in 2.258s
Invalid output
Exiting...
```

**Comment by quinnturner** [comment]
Thanks for the issue report. I agree with your assessment of the buffer not flushing. That would definitely be a good first place to look. As a side note, this project should introduce a unit test with a very large audit.

**Comment by quinnturner** [comment]
@callum-p Hi again, I was trying to reproduce the audit report with the `package.json`, but not having the `package-lock.json` made it so that I could only get ~250 vulnerabilities. At 250 vulnerabilities in v1.4.0 (just released), which uses `spawn` instead of `exec` made it not fail. I am hoping you can either test v1.4.0 or add the `package-lock.json` so I can test v1.4.0. Thanks!

**Comment by callum-p** [comment]
Hi @quinnturner thanks for fixing this. I can confirm it works as expected in v1.4.0 :+1:
