### ISSUE TITLE
Return exit codes based on validation

### ISSUE THREAD

**Issue by binarykitchen** [IBM/audit-ci#65]
Currently exit code 0 is always returned no matter whether there are vulnerabilities or not. Can you add that? Thanks

**Comment by quinnturner** [comment]
This is definitely the desired behaviour 👍

**Comment by quinnturner** [comment]
IMO it would be best if we returned the exit code received from the original audit _unless_ the exit code was non-zero due to a vulnerability that is whitelisted or below the specified level. This handles cases of other potential codes such as codes related to network errors, invalid registry, etc. At a minimum, it should return 1 if there's a non-whitelisted vulnerability above the level specified.

**Comment by dubbha** [comment]
> Currently exit code 0 is always returned no matter whether there are vulnerabilities or not.
Um.. Are you sure that is the case? I mean the whole idea of the wrapper is for it to fail 
> if there's a non-whitelisted vulnerability above the level specified
in a CI environment,which basically means it returns a non-zero exit-code. I am pretty sure that's exactly what's happening.

**Comment by binarykitchen** [comment]
Sorry I was wrong. When it fails it returns exit code of 1. When it passed, it returns 0. To verify this, run the `echo $?` command afterwards.
